### ISSUE TITLE
"N" read incorrectly as boolean

### ISSUE THREAD

**Issue by shabbychef** [viking/r-yaml#103]
Consider the following `example.yaml`:
```yaml
foo_text:        hi
columns:
  abc: "some string"
  N: "this will cause problems"
```
Calling
```R
read_yaml('~/example.yaml') %>% dput()
```
yields
```
list(foo_text = "hi", columns = list(abc = "some string", `FALSE` = "this will cause problems"))
```
That is to say the `N` is read incorrectly as a Boolean.
