### ISSUE TITLE
Support for yaml arrays?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [viking/r-yaml#77]
Hello, I'm trying to make an R implementation that would output this yaml:

```yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/[PROJECT_ID]/[IMAGE]', '.']
```

But I can't find some R object that supports the `['blah','blah']` bit.  It keeps putting it as individual entries.  It doesn't seem to be reversible in import and output either

e.g.

```r
yaml.load("steps:
+ - name: 'gcr.io/cloud-builders/docker'
+   args: ['build', '-t', 'gcr.io/[PROJECT_ID]/[IMAGE]', '.']")
#$steps
#$steps[[1]]
#$steps[[1]]$name
#[1] "gcr.io/cloud-builders/docker"
#
#$steps[[1]]$args
#[1] "build"                       "-t"                          "gcr.io/[PROJECT_ID]/[IMAGE]"
#[4] "."                          

yaml.load("steps:
+ - name: 'gcr.io/cloud-builders/docker'
+   args: ['build', '-t', 'gcr.io/[PROJECT_ID]/[IMAGE]', '.']") -> foo
as.yaml(foo)
```

...gives:

```yaml
steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - gcr.io/ddd
  - '.'
```

Is the desired output possible?
