### ISSUE TITLE
handles list column class

### ISSUE THREAD

**Issue by vbonhomme** [viking/r-yaml#85]
Hi there!
Thanks for this wonderful package.

I have data.frame-s that can contain list columns. 

For instance, I have the `chivas` object (with whisky bottles x;y outlines coordinates in `$coo`, and covariates in other columns).

```
chivas <- structure(list(coo = structure(list(chivas = structure(list(x = c(33, 
                                                                            32, 36, 141, 297, 329, 332, 273, 238, 232, 130, 113), y = c(437, 
                                                                                                                                        273, 125, 44, 52, 201, 349, 508, 668, 816, 770, 614)), row.names = c(NA, 
                                                                                                                                                                                                             -12L), class = c("coo_single", "tbl_df", "tbl", "data.frame"))), class = c("coo_list", 
                                                                                                                                                                                                                                                                                        "list")), type = structure(1L, .Label = c("beer", "whisky"), class = "factor"), 
                         fake = structure(3L, .Label = c("a", "b", "c", "d"), class = "factor"), 
                         size = -123.45, missing = NA), class = c("coo_tbl", "tbl_df", 
                                                                  "tbl", "data.frame"), row.names = c(NA, -1L))
```
The output is perfectly fine for general purpose: 
```
> cat(yaml::as.yaml(chivas))
coo:
  chivas:
    x:
    - 33.0
    - 32.0
    - 36.0
    - 141.0
    - 297.0
    - 329.0
    - 332.0
    - 273.0
    - 238.0
    - 232.0
    - 130.0
    - 113.0
    'y':
    - 437.0
    - 273.0
    - 125.0
    - 44.0
    - 52.0
    - 201.0
    - 349.0
    - 508.0
    - 668.0
    - 816.0
    - 770.0
    - 614.0
type: beer
fake: c
size: -123.45
missing: .na
```

Yet I would really love to know if it would be easy to retain classes (see second line), eg:

```
coo:
  class: coo_list
  chivas:
    x:
    - 33.0
    - 32.0
    - 36.0
    - 141.0
    - 297.0
    - 329.0
    - 332.0
    - 273.0
    - 238.0
    - 232.0
    - 130.0
    - 113.0
    'y':
    - 437.0
    - 273.0
    - 125.0
    - 44.0
    - 52.0
    - 201.0
    - 349.0
    - 508.0
    - 668.0
    - 816.0
    - 770.0
    - 614.0
type: beer
fake: c
size: -123.45
missing: .na
```

Or if you have a better idea for later parsing this?
Thanks a bunch,

Vincent

**Comment by viking** [comment]
Thanks for the kind words.

`as.yaml` and `yaml.load` have a way to process custom YAML tags (see https://yaml.org/spec/1.1/#id858600 for more info on tags). If you set the `"tag"` attribute, `as.yaml` will add them:

```r
attr(chivas, "tag") <- "chivas"
cat(yaml::as.yaml(chivas))
```

Produces:

```yaml
!<chivas>
coo:
  chivas:
    x:
    - 33.0
    - 32.0
    - 36.0
    - 141.0
    - 297.0
    - 329.0
    - 332.0
    - 273.0
    - 238.0
    - 232.0
    - 130.0
    - 113.0
    'y':
    - 437.0
    - 273.0
    - 125.0
    - 44.0
    - 52.0
    - 201.0
    - 349.0
    - 508.0
    - 668.0
    - 816.0
    - 770.0
    - 614.0
type: beer
fake: c
size: -123.45
missing: .na
```

Combined with a custom handler, you should be able to do what you're looking for:

```r
chivas <- structure(
  list(
    coo = structure(
      list(
        chivas = structure(
          list(
            x = c(33, 32, 36, 141, 297, 329, 332, 273, 238, 232, 130, 113),
            y = c(437, 273, 125, 44, 52, 201, 349, 508, 668, 816, 770, 614)
          ),
          row.names = c(NA, -12L),
          class = c("coo_single", "tbl_df", "tbl", "data.frame")
        )
      ),
      class = c("coo_list", "list")
    ),
    type = structure(
      1L,
      .Label = c("beer", "whisky"),
      class = "factor"
    ),
    fake = structure(
      3L,
      .Label = c("a", "b", "c", "d"),
      class = "factor"
    ),
    size = -123.45,
    missing = NA
  ),
  class = c("coo_tbl", "tbl_df", "tbl", "data.frame"),
  row.names = c(NA, -1L)
)
attr(chivas, "tag") <- "chivas"

chivas_handler <- function(obj) {
  attributes(obj$coo$chivas) <- list(
    row.names = c(NA, -length(obj$coo$chivas$x)),
    names = names(obj$coo$chivas)
  )
  class(obj$coo$chivas) <- c("coo_single", "tbl_df", "tbl", "data.frame")
  class(obj$coo) <- c("coo_list", "list")
  obj$type <- factor(obj$type, c("beer", "whisky"))
  obj$fake <- factor(obj$fake, c("a", "b", "c", "d"))
  attributes(obj) <- list(
    names = names(obj),
    row.names = c(NA, -length(obj$coo)),
    class = c("coo_tbl", "tbl_df", "tbl", "data.frame"),
    tag = "chivas"
  )
  obj
}

chivas2 <- yaml.load(as.yaml(chivas), handlers = list(chivas = chivas_handler))
print(all.equal(chivas2, chivas))
```
It takes some trial and error to make the result identical. I imagine you'd want to write the handler differently to make use of whatever packages you have loaded, but this should help you get going.

**Comment by vbonhomme** [comment]
Hi Jeremy,

Thanks A LOT for this enlightening example! This clarifies a lot how `handlers` work, not sure whether this is too minimally documented or (more likely) if I'm too minimally aware of yaml specs.

I think this could solve my problem, but I still wonder if tags could be used to handle specifically column classes when `as.yaml`-ing them. For instance if `class(df$col)=="foo"`  mark it with `!<foo>`? `<!chivas> was more the name of the list element but I'm looking for a way to "record" certain non-obvious column classes. What do you think? Does any of this make sense?

All the best,
Vincent

**Comment by viking** [comment]
`as.yaml` only looks at the `'tag'` attribute for adding YAML tags. However, `as.yaml` also lets you use custom handlers, so you could do this:

```r
obj <- list(x = 1:10, y = 11:20)
class(obj$x) <- 'foo'
class(obj$y) <- 'bar'

as_yaml_handlers <- list(
  foo = function(foo_obj) {
    attr(foo_obj, 'tag') <- 'foo'
    return(foo_obj)
  },
  bar = function(bar_obj) {
    attr(bar_obj, 'tag') <- 'bar'
    return(bar_obj)
  }
)

cat(yaml::as.yaml(obj, handlers = as_yaml_handlers))
```

The output is:
```yaml
x: !<foo>
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
'y': !<bar>
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
```
You could then have `'foo'` and `'bar'` handlers for `yaml.load` when parsing the document in order to process them however you like.
