### ISSUE TITLE
Is merge fully supported?

### ISSUE THREAD

**Issue by sfr** [viking/r-yaml#87]
I have a yaml like this
```yaml
defaults: &DEFAULTS
    use-tls: true
    verify-host: true
host1:
    <<: *DEFAULTS
    hostname: example1.com
host2:
    <<: *DEFAULTS
    hostname: example2.com
host3:
    <<: *DEFAULTS
    hostname: example3.com
    # we have a really, really good reason for doing this, really
    verify-host: false
...
```
when parsed, if looks like this:
```R
$defaults
$defaults$`use-tls`
[1] TRUE

$defaults$`verify-host`
[1] TRUE


$host1
$host1$`use-tls`
[1] TRUE

$host1$`verify-host`
[1] TRUE

$host1$hostname
[1] "example1.com"


$host2
$host2$`use-tls`
[1] TRUE

$host2$`verify-host`
[1] TRUE

$host2$hostname
[1] "example2.com"


$host3
$host3$`use-tls`
[1] TRUE

$host3$`verify-host`
[1] TRUE

$host3$hostname
[1] "example3.com"
```

I believe that value of `$host3$verify-host ` should be `FALSE`.

Is that a bug or it isn't supported yet?
